add_test([=[TypeRef.ValidScopeAndDottedName]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeRef.ValidScopeAndDottedName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeRef.ValidScopeAndDottedName]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeRef.InvalidScope]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeRef.InvalidScope]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeRef.InvalidScope]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeRef.ValidScopeAndNonDottedName]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeRef.ValidScopeAndNonDottedName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeRef.ValidScopeAndNonDottedName]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Module.ModuleNameExcludesDirectoryWin32Paths]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Module.ModuleNameExcludesDirectoryWin32Paths]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Module.ModuleNameExcludesDirectoryWin32Paths]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Module.ModuleNameExcludesDirectoryUnixPaths]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Module.ModuleNameExcludesDirectoryUnixPaths]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Module.ModuleNameExcludesDirectoryUnixPaths]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Module.ModuleNameWithoutDirectory]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Module.ModuleNameWithoutDirectory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Module.ModuleNameWithoutDirectory]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Module.EmptyName]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Module.EmptyName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Module.EmptyName]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Module.NullName]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Module.NullName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Module.NullName]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeDef.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeDef.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeDef.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeDef.DefineWithInterfaces]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeDef.DefineWithInterfaces]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeDef.DefineWithInterfaces]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeDef.DefineWithBase]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeDef.DefineWithBase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeDef.DefineWithBase]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeDef.NestedDefine]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeDef.NestedDefine]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeDef.NestedDefine]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeDef.SetProps]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeDef.SetProps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeDef.SetProps]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ModuleRef.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=ModuleRef.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ModuleRef.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MethodDef.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=MethodDef.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MethodDef.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MethodDef.DefineWithInvalidType]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=MethodDef.DefineWithInvalidType]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MethodDef.DefineWithInvalidType]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MethodDef.SetRva]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=MethodDef.SetRva]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MethodDef.SetRva]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MethodDef.SetProps]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=MethodDef.SetProps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MethodDef.SetProps]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[StandaloneSig.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=StandaloneSig.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[StandaloneSig.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MemberRef.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=MemberRef.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MemberRef.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MemberRef.SetParent]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=MemberRef.SetParent]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MemberRef.SetParent]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[TypeSpec.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=TypeSpec.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[TypeSpec.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Assembly.DefineNoPublicKey]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Assembly.DefineNoPublicKey]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Assembly.DefineNoPublicKey]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[AssemblyRef.DefineNoPublicKey]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=AssemblyRef.DefineNoPublicKey]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[AssemblyRef.DefineNoPublicKey]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Param.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Param.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Param.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Param.DefineWithConstant]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Param.DefineWithConstant]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Param.DefineWithConstant]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Param.DefineWithConstantString]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Param.DefineWithConstantString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Param.DefineWithConstantString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Param.DefineOutOfOrder]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=Param.DefineOutOfOrder]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Param.DefineOutOfOrder]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FieldMarshal.DefineAndDelete]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=FieldMarshal.DefineAndDelete]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FieldMarshal.DefineAndDelete]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[FieldRva.Define]=]  /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit/emit [==[--gtest_filter=FieldRva.Define]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[FieldRva.Define]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/DNMD/DNMD/_codeql_build_dir/test/emit SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  emit_TESTS TypeRef.ValidScopeAndDottedName TypeRef.InvalidScope TypeRef.ValidScopeAndNonDottedName Module.ModuleNameExcludesDirectoryWin32Paths Module.ModuleNameExcludesDirectoryUnixPaths Module.ModuleNameWithoutDirectory Module.EmptyName Module.NullName TypeDef.Define TypeDef.DefineWithInterfaces TypeDef.DefineWithBase TypeDef.NestedDefine TypeDef.SetProps ModuleRef.Define MethodDef.Define MethodDef.DefineWithInvalidType MethodDef.SetRva MethodDef.SetProps StandaloneSig.Define MemberRef.Define MemberRef.SetParent TypeSpec.Define Assembly.DefineNoPublicKey AssemblyRef.DefineNoPublicKey Param.Define Param.DefineWithConstant Param.DefineWithConstantString Param.DefineOutOfOrder FieldMarshal.DefineAndDelete FieldRva.Define)
